//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockInProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depart
    {
        public string DepartID { get; set; }
        public string DepartName { get; set; }
        public string DepartNameEn { get; set; }
        public string EmplID { get; set; }
        public string TelNo { get; set; }
        public Nullable<short> Male { get; set; }
        public Nullable<short> Female { get; set; }
        public string JobSchID { get; set; }
        public string Explain { get; set; }
        public string Memo { get; set; }
        public string UdefT1 { get; set; }
        public string UdefT2 { get; set; }
        public string UdefT3 { get; set; }
        public string UdefD1 { get; set; }
        public string UdefD2 { get; set; }
        public Nullable<decimal> UdefN1 { get; set; }
        public Nullable<decimal> UdefN2 { get; set; }
        public string AppxPath { get; set; }
    }
}
